### ISSUE TITLE
Seems the website www.getnews.tech is down

### ISSUE THREAD

**Issue by gbstan** [omgimanerd/getnews.tech#14]
It seems the website is down as no request have been going through for the past 2 days.

**Comment by omgimanerd** [comment]
Ugh mongod is giving me such a massive headache, I'm going to migrate off of it.

**Comment by omgimanerd** [comment]
Sorry for the inconvenience, let find a less annoying db solution.

**Comment by omgimanerd** [comment]
Migrated to Redis for URL shortening as of 3b45d8a5b9c8078737dc352315f47b6c4a259a40

This means all previous shortened urls are no longer valid (also because I accidentally firewalled myself out of the box hosting this service and I had to delete and remake it :shrug: ).

I should probably create some form of monitoring as well so that I know if getnews.tech breaks instead of learning about it from someone filing an issue.
