### ISSUE TITLE
/help: blue text is not readable

### ISSUE THREAD

**Issue by chubin** [omgimanerd/getnews.tech#9]
I have checked the new `/:help` page, it is very cool, but I would suggest several improvements:

1. Blue text is unreadable on black background (at least on my terminal, and I have pretty default settings i.e. many others will have this problem too)
2. Valid countries are highlighted, and valid categories not; it would be better to make it consistent
3. Would it be possible to make time direction configurable (top -> down, blogstyle or down -> top, log style)?

And the last but not least, strange, maybe you've changed something in the search algorithm, but now it is impossible to find anything related to programming languages news.
I tried to search for `rust`, `elm`, `python` and the service delivered `Trump raised Biden with Xi` etc. But I think that it is just some configuration bug, and you will fix it soon.

**Comment by omgimanerd** [comment]
Thanks so much for your feedback and help testing this application! I really appreciate the input.

1/2. I have a black background and was able to read it, but I can see why this is an issue, I think it would be best left unhighlighted.
3. Yep, I'll add this feature!

Thanks for bringing the search bug to my attention. I believe this is due to the fact that I switched over to hitting the /topHeadlines endpoint of the News API, which only surfaces recent news, which often does not have much about programming. Let me see if I can find a solution to this.

**Comment by chubin** [comment]
I've just tested different countries queries, and it works pretty decent, I like it. Of course, it would be great to have some domain name (or may be just getnews.tech, without any subdomain) for global news, or maybe some subdomains for the most important global topics, i.e. `programming` or `tech` or something like that. Of course, I understand, that you can use only the features that are provided by the API, but still it could be possible to map some most important queries to domain names.

**Comment by omgimanerd** [comment]
```
curl getnews.tech
```
defaults to global news and you can specify `category=technology` to query for global tech news or localized to any country. I've also added a `reverse` and `nocolor` flag if you want the results in reverse chronological order or uncolored.

**Comment by chubin** [comment]
@omgimanerd Thank you for the fixes.

I still do not understand, how I can get news about programming languages, as it was possible before.

I tried:
```
curl getnews.tech/rust
curl getnews.tech/rust?category=technology
curl us.getnews.tech/rust?category=technology
```

and I did not manage to find any working combination
